services:
  eduport:
    build:
      dockerfile: ./docker/eduport.Dockerfile
    ports:
      - "9000:80"
      - "9001:81"

  frontend:
    build:
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules:rw

volumes:
  frontend_node_modules:
